add_rules("mode.debug", "mode.release")
target("mirai-qt")
    add_rules("qt.application")
    add_files("mirai-qt/*.cpp")
    add_files("mirai-qt/*.ui")
    add_files("mirai-qt/*.h")
    add_frameworks("QtWidgets","QtNetwork")
target("onebot")
    add_rules("qt.console")
    add_files("onebot/*.cpp")
    add_frameworks("QtNetwork","QtWebsockets")